### ISSUE TITLE
Some problems about Deepship dataset training and test based on CMoE

### ISSUE THREAD

**Issue by LiMnRa** [xy980523/UATR-CMoE#2]
您好：
      我们团队目前在训练和识别Deepship数据集，看到您的这篇文章《Unraveling Complex Data Diversity in Underwater Acoustic Target Recognition through Convolution-based Mixture of Experts》很感兴趣，并按照您文中给出的代码链接和展示的参数进行了测试。
      但是我们的结果跟您文中的结果差了6.6%（CMoE+balance，Mel谱特征），我们未能分析出问题在哪里，所以想请您看一下我们的训练参数和结果（附件：CmoE测试结果整理20240426.docx），给予一些意见和建议。
      另外，CMoE模型代码中的 attention pooling layer 和 expert layers 的结构似乎和文中的描述（ [1] 以及 Table 1）对不上，也想劳烦您解答一下。
      我们很期待您的回复，您的回复对于我们的工作会有很大的助力。

**[1]**The attention pooling layer incorporates global average pooling and multi-head self-attention operations, allowing for the assignment of dynamic weights to different regions of the feature map.

**附件：**

[CmoE测试结果整理20240426.docx](https://github.com/xy980523/UATR-CMoE/files/15125922/CmoE.20240426.docx)

@xy980523

**Comment by YuanX9** [comment]
1. 有关测试集的id，文中确实出现了typo，02编号后的24、25、27应该是04、05、07，感谢您的提醒
2. 有关attention pooling layer，你可以将代码中的self.avgpool = nn.AdaptiveAvgPool2d((1, 1))改成：
```
import torch.nn.functional as F

class AttentionPool2d(nn.Module):
    def __init__(self, spacial_dim: int, embed_dim: int, num_heads: int, output_dim: int = None):
        super().__init__()
        self.positional_embedding = nn.Parameter(torch.randn(spacial_dim ** 2 + 1, embed_dim) / embed_dim ** 0.5)
        self.k_proj = nn.Linear(embed_dim, embed_dim)
        self.q_proj = nn.Linear(embed_dim, embed_dim)
        self.v_proj = nn.Linear(embed_dim, embed_dim)
        self.c_proj = nn.Linear(embed_dim, output_dim or embed_dim)
        self.num_heads = num_heads

    def forward(self, x):
        x = x.reshape(x.shape[0], x.shape[1], x.shape[2] * x.shape[3]).permute(2, 0, 1)  # NCHW -> (HW)NC
        x = torch.cat([x.mean(dim=0, keepdim=True), x], dim=0)  # (HW+1)NC
        x = x + self.positional_embedding[:, None, :].to(x.dtype)  # (HW+1)NC
        x, _ = F.multi_head_attention_forward(
            query=x, key=x, value=x,
            embed_dim_to_check=x.shape[-1],
            num_heads=self.num_heads,
            q_proj_weight=self.q_proj.weight,
            k_proj_weight=self.k_proj.weight,
            v_proj_weight=self.v_proj.weight,
            in_proj_weight=None,
            in_proj_bias=torch.cat([self.q_proj.bias, self.k_proj.bias, self.v_proj.bias]),
            bias_k=None,
            bias_v=None,
            add_zero_attn=False,
            dropout_p=0,
            out_proj_weight=self.c_proj.weight,
            out_proj_bias=self.c_proj.bias,
            use_separate_proj_weight=True,
            training=self.training,
            need_weights=False
        )

        return x[0]
        
self.attnpool = AttentionPool2d(spacial_dim, embed_dim, heads, output_dim)  # 这里 dim 取决于输入特征维度
```
相比普通的avgpool，attnpool的性能上限更高（如文中结果所示），但是需要花费较多精力在调参上，所以我并不是非常推荐使用。由于领域限制，我没有权限公开训练代码，所以选择给出容易带来较稳定性能的avgpool，而非attnpool。

3. 训练结果与文中结果产生较大偏差的原因可能有两点：
a) 验证集的划分。当验证集数据分布与测试集有较大偏差时，可能会导致性能较低。你可以尝试重新随机挑选验证集。
b) 你可以尝试一些简单的数据扩增，比如mixup或者cutmix

**Comment by LiMnRa** [comment]
非常感谢您的回复，我们会参考您的建议做进一步的测试。
